[Physics]
FixUninitialisedArticulatedPhysicsObjectCloneRelativeCentreOfMassAndInertiaMatrixUpdateInterval=1

[Visual]
; HUDCoinDepth
; 	Set whether or not the coin on the HUD will have depth.
HUDCoinDepth=1

[Crashes]
; FixCarDeletedWhileLoadingCONFileCrash
; 	Set whether or not the game will crash if a car is deleted before it's CON file is finished loading.
FixCarDeletedWhileLoadingCONFileCrash=1

; FixZoneLoadOnExitCrash
; 	Set whether or not the game will crash if the game tries to load a zone while exiting.
FixZoneLoadOnExitCrash=1