Game.SelectMission("m4");

Game.SetMissionResetPlayerInCar("m4_williecar");
Game.SetDynaLoadData("l1z3.p3d;l1r2.p3d;l1r3.p3d;");
Game.SetNumValidFailureHints( 2 );
Game.InitLevelPlayerVehicle("willi_v","m4_willystart","OTHER");
Game.SetForcedCar();

Game.AddStage(10);
	Game.RESET_TO_HERE();
	Game.SetStageMessageIndex(266);
	Game.SetHUDIcon( "burns" );
	Game.SetStageCharacterModel("willie");
	Game.AddStageVehicle("smith_v","m4_burnscar","NULL","Missions\\level01\\M4evade.con", "smithers");
	Game.AddObjective("delivery","neither");
		Game.AddCollectible("m4_evi1","bloodbag");
		Game.AddCollectible("m4_evi2","radio");
		Game.AddCollectible("m4_evi3","roadkill");
		Game.AddCollectible("m4_evi5","fish");
		Game.AddCollectible("m4_evi7","inhaler");
		Game.AddCollectible("m4_evi9","litter");
	Game.CloseObjective();
	Game.StageStartMusicEvent("M4_start");
	Game.ShowStageComplete();
	Game.SetStageMusicAlwaysOn();
Game.CloseStage();

Game.AddStage();
	Game.SetStageMessageIndex(267);
	Game.SetHUDIcon( "smithers" );
	Game.SetStageCharacterModel("willie");
	Game.AddStageWaypoint( "m4_burnspath1" );
	Game.AddStageWaypoint( "m4_burnspath2" );
	Game.AddStageWaypoint( "m4_burnspath3" );
	Game.AddStageWaypoint( "m4_burnspath4" );
	Game.AddObjective("dump", "neither");
		Game.SetObjTargetVehicle("smith_v");
		Game.ActivateVehicle("smith_v","NULL","evade");
		Game.SetVehicleAIParams( "smith_v", -10, -9 );
		Game.AddCollectible("m4_burnev_1","molemanr");
		Game.AddCollectible("m4_burnev_2","i_folder");
		Game.AddCollectible("m4_burnev_3","map");
		Game.BindCollectibleTo(0, 0);
		Game.BindCollectibleTo(1, 1);
		Game.BindCollectibleTo(2, 2);
		Game.BindCollectibleTo(3, 4);
		Game.BindCollectibleTo(4, 5);
		Game.BindCollectibleTo(5, 6);
		Game.BindCollectibleTo(6, 7);
		Game.SetCollectibleEffect("bonestorm_explosion");
	Game.CloseObjective();
	Game.AddCondition("followdistance");
		Game.SetFollowDistances(0,200);
		Game.SetCondTargetVehicle("smith_v");
	Game.CloseCondition();
	Game.ShowStageComplete();
	Game.SetFadeOut(1.0);
	Game.SwapInDefaultCar();
	Game.SetSwapDefaultCarLocator("m4_williecar");
	Game.SetSwapForcedCarLocator("m4_williecarend");
	Game.SetSwapPlayerLocator("m4_willieend");
Game.CloseStage();

Game.AddStage("final");
	Game.SetStageMessageIndex(11);
	Game.SetStageCharacterModel("willie");
	Game.AddObjective("timer");
		Game.AddStageCharacter ("homer", "m4_willieend", "", "", "");
		Game.SetDurationTime(3);
	Game.CloseObjective();
Game.CloseStage();


Game.CloseMission();
