Game.SelectMission("m5");

Game.SetMissionResetPlayerInCar("m5_barneycar"); 
Game.SetDynaLoadData("l1z1.p3d;l1r1.p3d;l1r7.p3d;");
Game.UsePedGroup( 0 ); 
Game.InitLevelPlayerVehicle("plowk_v","m5_barneycar","OTHER");
Game.SetForcedCar();

Game.AddStage();
	Game.RESET_TO_HERE();
	Game.SetStageMessageIndex(268);
	Game.SetHUDIcon("spack");
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("delivery","neither");
		Game.AddCollectible("m5_ob1","spack");
		Game.AddCollectible("m5_ob2","spack");
		Game.AddCollectible("m5_ob3","spack");
		Game.AddCollectible("m5_ob4","spack");
		Game.AddCollectible("m5_ob5","spack");
		Game.AddCollectible("m5_ob6","spack");
		Game.AddCollectible("m5_ob7","spack");
		Game.AddCollectible("m5_ob8","spack");
		Game.AddCollectible("m5_ob9","spack");
		Game.AddCollectible("m5_ob10","spack");
		Game.AddCollectible("m5_ob11","spack");
		Game.AddCollectible("m5_ob12","spack");
		Game.AddCollectible("m5_ob13","spack");
		Game.AddCollectible("m5_ob14","spack");
		Game.AddCollectible("m5_ob15","spack");
		Game.RemoveNPC("barney");
	Game.CloseObjective();
	Game.StageStartMusicEvent("M5_start");
	Game.SetStageMusicAlwaysOn();
	Game.ShowStageComplete();
Game.CloseStage();

Game.AddStage(0);
	Game.SetStageMessageIndex(12);
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("getin", "neither");
		Game.SetObjTargetVehicle("current");
	Game.CloseObjective();
Game.CloseStage();

Game.AddStage(0);
	Game.SetStageMessageIndex(269);
	Game.SetHUDIcon("moehouse");
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("goto");
		Game.SetDestination("m5_moes", "carsphere");
		Game.SetCollectibleEffect("wrench_collect");
	Game.CloseObjective();
	Game.AddCondition( "damage" );
		Game.SetCondMinHealth( 0.0 );
		Game.SetCondTargetVehicle( "current" );
	Game.CloseCondition();
Game.CloseStage();

Game.AddStage();
	Game.SetStageMessageIndex(268);
	Game.SetHUDIcon("spack");
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("delivery","neither");
		Game.AddCollectible("m5_moeob1","spack");
		Game.AddCollectible("m5_moeob2","spack");
		Game.AddCollectible("m5_moeob3","spack");
		Game.AddCollectible("m5_moeob4","spack");
		Game.AddCollectible("m5_moeob5","spack");
	Game.CloseObjective();
	Game.ShowStageComplete();
Game.CloseStage();

Game.AddStage(0);
	Game.SetStageMessageIndex(157);
	Game.SetHUDIcon("pwrplant");
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("goto");
		Game.SetDestination("m5_pp", "carsphere");
		Game.SetCollectibleEffect("wrench_collect");
	Game.CloseObjective();
	Game.AddCondition( "damage" );
		Game.SetCondMinHealth( 0.0 );
		Game.SetCondTargetVehicle( "current" );
	Game.CloseCondition();
Game.CloseStage();

Game.AddStage();
	Game.SetStageMessageIndex(268);
	Game.SetHUDIcon("spack");
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("delivery","neither");
		Game.AddCollectible("m5_ppob1","spack");
		Game.AddCollectible("m5_ppob2","spack");
		Game.AddCollectible("m5_ppob3","spack");
		Game.AddCollectible("m5_ppob4","spack");
		Game.AddCollectible("m5_ppob5","spack");
		Game.AddCollectible("m5_ppob6","spack");
		Game.AddCollectible("m5_ppob7","spack");
		Game.AddCollectible("m5_ppob8","spack");
		Game.AddCollectible("m5_ppob9","spack");
		Game.AddCollectible("m5_ppob10","spack");
		Game.SetFadeOut(1.0);
		Game.SwapInDefaultCar();
		Game.SetSwapDefaultCarLocator("m5_barneycar");
		Game.SetSwapForcedCarLocator("m5_barneycar");
		Game.SetSwapPlayerLocator("m5_barneyend");
		Game.CloseObjective();
Game.CloseStage();

Game.AddStage("final");
	Game.SetStageCharacterModel("barney", "barney");
	Game.AddObjective("timer");
		Game.AddStageCharacter ("homer", "m5_barneyend", "", "", "");
		Game.SetDurationTime(3);
	Game.CloseObjective();
Game.CloseStage();

Game.CloseMission();